### ISSUE TITLE
configurable output directory

### ISSUE THREAD

**Issue by morandd** [AndGem/osm_extract_polygon#30]
Small feature request: could you make the output directory configurable via the command line?

If this were configurable, this utility would be thread-safe.  To illustrate, I am using this to extract admin boundaries from national OSM files by running it several times with min=7 max=7, min=6 max=6, etc. But since the output directory is always <input file>_polygons/ these commands must be run in sequence, when logically they could be run in parallel using GNU parallel for example.

**Comment by AndGem** [comment]
Hey @morandd ,

thanks for the suggestion. This is an easy addition to do (and I'm just preparing the release of the new version). Hope this helps you.

While I think it's a good idea to add this parameter, I'm concerned that maybe the speedup using `parallel` would be small, because I fear that this process is mostly IO bound and therefore it would not really help much. 

Anyway, the new release 0.4.2 (https://github.com/AndGem/osm_extract_polygon/releases/tag/v.0.4.2) should solve your issue.

Would be happy to hear back if it works.

**Comment by morandd** [comment]
Thank you so much. Could you add binaries (osm_extract_polygon-linux-amd64) so I can test it without having to install the rust compiler?

**Comment by AndGem** [comment]
good catch. The system should have done it automatically. I'll try to fix it and ping you once this works.

**Comment by AndGem** [comment]
after some fights with dependencies: here it is https://github.com/AndGem/osm_extract_polygon/releases/tag/v.0.4.2 with linux binaries

**Comment by morandd** [comment]
works well. Much appreciated
