### ISSUE TITLE
"_1", "_2", etc suffixes are nondeterministic

### ISSUE THREAD

**Issue by morandd** [AndGem/osm_extract_polygon#33]
It seems that the  "_1", "_2", etc suffixing added to regions with identical names is nondeterministic. That is, if you run this on a region like Peru the regions  Amazonas_1, Amazonas_2, and Amazonas_3 can refer to different regions on repeated runs. Likewise, if two different people run this program they may get different Amazonas_1 regions. I presume this is an artifact resulting from parallelism.

To fix this, perhaps instead of using the _1, _2 etc suffix, use the Relation ID or Way ID instead. That will be both unique and deterministic.

**Comment by AndGem** [comment]
Hi @morandd ,

thanks for filing this issue. I think you are right about the root cause being the parallelism. I've changed the behavior by forming the filename as `<Region Name>_<Relation ID>` if there are duplicates. That should in theory work. 

Would be glad to hear back from you if it works. (Please check release `0.4.3`).

**Comment by morandd** [comment]
The 0.4.3 fix works.
